/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package labs.java.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ApplicationConfiguratorTest {
}
